### PR TITLE
fix: make getPeerId return the target peer id from relay addrs

### LINKED ISSUE #319: getPeerId can return an unexpected peer id
`.getPeerId()` returns the peer id from a multiaddr if one is present but it may not be the one we expect.

If the mulitaddr is a relay address but doesn't have the relay client's peer id in the address, the peer id returned is that of the relay.

I believe the intention of `.getPeerId` is to return the peer id of the remote peer that can be dialled using the peer id, not just any peer id that happens to be in the multiaddr.

We could fix this by treating `p2p-circuit` as a special case and returning the value part of the `p2p-circuit` tuple if found, or more generally by only returning a peer id if it's in the final tuple?

Refs: https://github.com/libp2p/js-libp2p/pull/1680

### PR DESCRIPTION
**Pull request by achingbrain**
If a p2p-circuit address doesn't contain the `/p2p/QmFoo` tuple for the target peer, `getPeerId` returns the peer id of the relay which is not what you'd expect.

The fix here is for relay addresses, to return the peer id of the target and never the relay.

Fixes #319

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -655,14 +655,21 @@ class DefaultMultiaddr implements Multiaddr {
...
+      this.stringTuples().forEach(([code, name]) => {
+        if (code === names.p2p.code) {
+          tuples.push([code, name])
+        }
+
+        // if this is a p2p-circuit address, return the target peer id if present
+        // not the peer id of the relay
+        if (code === names['p2p-circuit'].code) {
+          tuples = []
         }
```
Comment (SgtPooki) [inline src/index.ts:669]: i find it confusing that we push to tuples and then empty tuples if p2p-circuit is found. 

Could this result in (eventually longer and currently unknown) multiaddr tuples being removed that shouldn't? Instead, should we just not call `tuples.push` if it's the p2p-circuit case for the current code?

File: test/index.spec.ts [hunk 2]
```diff
@@ -997,6 +997,11 @@ describe('helpers', () => {
         multiaddr('/p2p-circuit/p2p/12D3KooWNvSZnPi3RrhrTwEY4LuuBeB6K6facKUCJcyWG1aoDd2p').getPeerId()
       ).to.equal('12D3KooWNvSZnPi3RrhrTwEY4LuuBeB6K6facKUCJcyWG1aoDd2p')
     })
+    it('does not extract a peer Id from a circuit relay multiaddr where only the relay peer id is present', () => {
+      expect(
+        multiaddr('/ip4/127.0.0.1/tcp/123/p2p/bafzbeigweq4zr4x4ky2dvv7nanbkw6egutvrrvzw6g3h2rftp7gidyhtt4/p2p-circuit').getPeerId()
+      ).to.be.null()
+    })
```
Comment (SgtPooki) [inline test/index.spec.ts:1004]: the positive test case (peerId of relayed peer exists) already exists in the tests from what I can see. However, do we need to check a case where we have something like 

`/ip4/127.0.0.1/tcp/123/p2p/bafzbeigweq4zr4x4ky2dvv7nanbkw6egutvrrvzw6g3h2rftp7gidyhtt4/p2p-circuit/p2p/bafzbeidt255unskpefjmqb2rc27vjuyxopkxgaylxij6pw35hhys4vnyp4` 

to make sure the correct peer ID is returned when there are two?

**Review by SgtPooki — APPROVED** [review]
approved, but questions/concerns.

File: test/index.spec.ts (hunk 2 above)
Comment (achingbrain) [reply test/index.spec.ts:1004]: I think we have this in the `'extracts the correct peer Id from a circuit multiaddr'` test?

File: src/index.ts (hunk 1 above)
Comment (achingbrain) [reply src/index.ts:649]: I don't think so, because circuit relay addresses are not supposed to be relayed themselves so whatever is after `p2p-circuit` should be what we are interested in.

We reset the tuples because whatever was before the `p2p-circuit` tuple is the relay address and we're trying to extract the PeerId of the target, not the relay.

It's trying to handle the case of:

`/ip4/foo/p2p/QmRelay/p2p-circuit` -> should return `null` not `QmRelay`
